"""Procedural gradient and solid-colour backgrounds — no key, no network, no browser."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .... import ffmpeg
from ....config import Settings, get_settings
from ....core.assets import Licence, Provenance
from ....core.errors import InvalidInput
from . import BackgroundClip, BackgroundRequest

LICENCE = Licence(
    name="CC0-1.0",
    url="https://creativecommons.org/publicdomain/zero/1.0/",
    attribution="generated by reel-machine",
)


def _hex(value: str) -> str:
    text = (value or "").strip().lstrip("#")
    return f"0x{text}" if len(text) == 6 else "0x101820"


class GradientBackgroundProvider:
    name = "gradient"

    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()

    def missing(self) -> list[str]:
        return []

    def describe(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "group": "backgrounds",
            "description": "Animated gradient generated with ffmpeg (no key, no network)",
            "missing": [],
        }

    def fetch(self, request: BackgroundRequest, *, dest_dir: Path) -> BackgroundClip:
        settings = self.settings
        duration_s = max(0.5, request.duration_ms / 1000.0)
        out = dest_dir / "background-gradient.mp4"
        colors = request.colors or ["#0e1621", "#1f3b4d"]
        first = colors[0]
        second = colors[1] if len(colors) > 1 else first
        cmd = [
            settings.ffmpeg, "-hide_banner", "-nostdin", "-y",
            "-f", "lavfi",
            "-i", (
                f"gradients=s={request.width}x{request.height}:c0={_hex(first)}:c1={_hex(second)}:"
                f"speed={request.speed}"
            ),
            "-t", f"{duration_s:.3f}", "-r", "30",
            "-c:v", "libx264", "-preset", settings.preset, "-crf", str(settings.crf),
            "-pix_fmt", "yuv420p", str(out),
        ]
        try:
            ffmpeg.run(cmd)
        except ffmpeg.FFmpegError as exc:
            raise InvalidInput(
                "this ffmpeg cannot generate the procedural gradient background",
                hint="use background kind=file, or upgrade ffmpeg (the gradients source needs 4.4+)",
                details={"stderr": str(exc)[-300:]},
            ) from exc
        return BackgroundClip(
            path=out,
            provenance=Provenance(provider="reelmachine", source="gradient"),
            licence=LICENCE,
            width=request.width,
            height=request.height,
            duration_ms=int(duration_s * 1000),
        )


class SolidBackgroundProvider:
    """A deterministic flat background — the fake a test or a dry run can rely on."""

    name = "fake"

    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()

    def missing(self) -> list[str]:
        return []

    def describe(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "group": "backgrounds",
            "description": "A flat colour clip (deterministic, offline)",
            "missing": [],
        }

    def fetch(self, request: BackgroundRequest, *, dest_dir: Path) -> BackgroundClip:
        settings = self.settings
        duration_s = max(0.5, request.duration_ms / 1000.0)
        colour = _hex((request.colors or ["#101820"])[0])
        out = dest_dir / "background-solid.mp4"
        ffmpeg.run([
            settings.ffmpeg, "-hide_banner", "-nostdin", "-y",
            "-f", "lavfi", "-i", f"color=c={colour}:s={request.width}x{request.height}:r=30",
            "-t", f"{duration_s:.3f}",
            "-c:v", "libx264", "-preset", settings.preset, "-crf", str(settings.crf),
            "-pix_fmt", "yuv420p", str(out),
        ])
        return BackgroundClip(
            path=out,
            provenance=Provenance(provider=self.name, source="solid"),
            licence=LICENCE,
            width=request.width,
            height=request.height,
            duration_ms=int(duration_s * 1000),
        )
